# Form implementation generated from reading ui file 'src/ui/ui_add_bookmark_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddBookmarkDialog(object):
    def setupUi(self, AddBookmarkDialog):
        AddBookmarkDialog.setObjectName("AddBookmarkDialog")
        AddBookmarkDialog.resize(500, 341)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddBookmarkDialog)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.url_label = QtWidgets.QLabel(parent=AddBookmarkDialog)
        self.url_label.setStyleSheet("font-weight: bold;")
        self.url_label.setObjectName("url_label")
        self.verticalLayout.addWidget(self.url_label)
        self.url_edit = QtWidgets.QLineEdit(parent=AddBookmarkDialog)
        self.url_edit.setObjectName("url_edit")
        self.verticalLayout.addWidget(self.url_edit)
        self.title_label = QtWidgets.QLabel(parent=AddBookmarkDialog)
        self.title_label.setStyleSheet("font-weight: bold;")
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.title_edit = QtWidgets.QLineEdit(parent=AddBookmarkDialog)
        self.title_edit.setObjectName("title_edit")
        self.verticalLayout.addWidget(self.title_edit)
        self.description_label = QtWidgets.QLabel(parent=AddBookmarkDialog)
        self.description_label.setStyleSheet("font-weight: bold;")
        self.description_label.setObjectName("description_label")
        self.verticalLayout.addWidget(self.description_label)
        self.description_edit = QtWidgets.QTextEdit(parent=AddBookmarkDialog)
        self.description_edit.setAcceptRichText(False)
        self.description_edit.setObjectName("description_edit")
        self.verticalLayout.addWidget(self.description_edit)
        self.tags_label = QtWidgets.QLabel(parent=AddBookmarkDialog)
        self.tags_label.setStyleSheet("font-weight: bold;")
        self.tags_label.setObjectName("tags_label")
        self.verticalLayout.addWidget(self.tags_label)
        self.tags_edit = QtWidgets.QLineEdit(parent=AddBookmarkDialog)
        self.tags_edit.setObjectName("tags_edit")
        self.verticalLayout.addWidget(self.tags_edit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setSpacing(10)
        self.button_layout.setObjectName("button_layout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.button_layout.addItem(spacerItem1)
        self.cancel_btn = QtWidgets.QPushButton(parent=AddBookmarkDialog)
        self.cancel_btn.setObjectName("cancel_btn")
        self.button_layout.addWidget(self.cancel_btn)
        self.add_btn = QtWidgets.QPushButton(parent=AddBookmarkDialog)
        self.add_btn.setStyleSheet("font-weight: bold;")
        self.add_btn.setObjectName("add_btn")
        self.button_layout.addWidget(self.add_btn)
        self.verticalLayout.addLayout(self.button_layout)

        self.retranslateUi(AddBookmarkDialog)
        QtCore.QMetaObject.connectSlotsByName(AddBookmarkDialog)

    def retranslateUi(self, AddBookmarkDialog):
        _translate = QtCore.QCoreApplication.translate
        AddBookmarkDialog.setWindowTitle(_translate("AddBookmarkDialog", "Добавить закладку"))
        self.url_label.setText(_translate("AddBookmarkDialog", "URL:"))
        self.url_edit.setPlaceholderText(_translate("AddBookmarkDialog", "https://example.com"))
        self.title_label.setText(_translate("AddBookmarkDialog", "Название (опционально):"))
        self.title_edit.setPlaceholderText(_translate("AddBookmarkDialog", "Введите название закладки"))
        self.description_label.setText(_translate("AddBookmarkDialog", "Описание (опционально):"))
        self.description_edit.setPlaceholderText(_translate("AddBookmarkDialog", "Добавьте описание закладки..."))
        self.tags_label.setText(_translate("AddBookmarkDialog", "Теги (через запятую, опционально):"))
        self.tags_edit.setPlaceholderText(_translate("AddBookmarkDialog", "работа, проекты, ссылки"))
        self.cancel_btn.setText(_translate("AddBookmarkDialog", "Отмена"))
        self.add_btn.setText(_translate("AddBookmarkDialog", "Добавить"))
