# Form implementation generated from reading ui file 'src/ui/bookmarks_widget.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BookmarksWidget(object):
    def setupUi(self, BookmarksWidget):
        BookmarksWidget.setObjectName("BookmarksWidget")
        BookmarksWidget.resize(600, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(BookmarksWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(parent=BookmarksWidget)
        self.title_label.setStyleSheet("font-weight: bold; font-size: 14px; margin-bottom: 5px;")
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.search_layout = QtWidgets.QHBoxLayout()
        self.search_layout.setSpacing(5)
        self.search_layout.setObjectName("search_layout")
        self.search_input = QtWidgets.QLineEdit(parent=BookmarksWidget)
        self.search_input.setObjectName("search_input")
        self.search_layout.addWidget(self.search_input)
        self.clear_search_btn = QtWidgets.QPushButton(parent=BookmarksWidget)
        self.clear_search_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.clear_search_btn.setObjectName("clear_search_btn")
        self.search_layout.addWidget(self.clear_search_btn)
        self.verticalLayout.addLayout(self.search_layout)
        self.bookmarks_list = QtWidgets.QListWidget(parent=BookmarksWidget)
        self.bookmarks_list.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.bookmarks_list.setStyleSheet("QListWidget {\n"
"    background-color: palette(base);\n"
"    border: 1px solid palette(mid);\n"
"    border-radius: 3px;\n"
"}\n"
"QListWidget::item {\n"
"    border: none;\n"
"    padding: 0px;\n"
"    margin: 2px;\n"
"}\n"
"QListWidget::item:selected {\n"
"    background-color: transparent;\n"
"}\n"
"QListWidget::item:hover {\n"
"    background-color: transparent;\n"
"}")
        self.bookmarks_list.setObjectName("bookmarks_list")
        self.verticalLayout.addWidget(self.bookmarks_list)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setSpacing(10)
        self.button_layout.setObjectName("button_layout")
        self.add_btn = QtWidgets.QPushButton(parent=BookmarksWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/add.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.add_btn.setIcon(icon)
        self.add_btn.setObjectName("add_btn")
        self.button_layout.addWidget(self.add_btn)
        self.refresh_btn = QtWidgets.QPushButton(parent=BookmarksWidget)
        self.refresh_btn.setObjectName("refresh_btn")
        self.button_layout.addWidget(self.refresh_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.button_layout.addItem(spacerItem)
        self.stats_label = QtWidgets.QLabel(parent=BookmarksWidget)
        self.stats_label.setStyleSheet("color: palette(mid); font-size: 11px; margin-top: 5px;")
        self.stats_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.stats_label.setObjectName("stats_label")
        self.button_layout.addWidget(self.stats_label)
        self.verticalLayout.addLayout(self.button_layout)

        self.retranslateUi(BookmarksWidget)
        QtCore.QMetaObject.connectSlotsByName(BookmarksWidget)

    def retranslateUi(self, BookmarksWidget):
        _translate = QtCore.QCoreApplication.translate
        BookmarksWidget.setWindowTitle(_translate("BookmarksWidget", "Закладки"))
        self.title_label.setText(_translate("BookmarksWidget", "Веб-закладки"))
        self.search_input.setPlaceholderText(_translate("BookmarksWidget", "Поиск закладок..."))
        self.clear_search_btn.setText(_translate("BookmarksWidget", "❌"))
        self.clear_search_btn.setToolTip(_translate("BookmarksWidget", "Очистить поиск"))
        self.add_btn.setText(_translate("BookmarksWidget", "➕ Добавить закладку"))
        self.refresh_btn.setText(_translate("BookmarksWidget", "🔄 Обновить"))
        self.refresh_btn.setToolTip(_translate("BookmarksWidget", "Обновить список закладок"))
        self.stats_label.setText(_translate("BookmarksWidget", "Закладок: 0"))
