# Form implementation generated from reading ui file 'src/ui/bookmarks_widget.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BookmarksWidget(object):
    def setupUi(self, BookmarksWidget):
        BookmarksWidget.setObjectName("BookmarksWidget")
        BookmarksWidget.resize(600, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(BookmarksWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(parent=BookmarksWidget)
        self.title_label.setStyleSheet("font-weight: bold; font-size: 14px; margin-bottom: 5px;")
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.search_layout = QtWidgets.QHBoxLayout()
        self.search_layout.setSpacing(5)
        self.search_layout.setObjectName("search_layout")
        self.search_input = QtWidgets.QLineEdit(parent=BookmarksWidget)
        self.search_input.setObjectName("search_input")
        self.search_layout.addWidget(self.search_input)
        self.add_btn = QtWidgets.QPushButton(parent=BookmarksWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/add.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.add_btn.setIcon(icon)
        self.add_btn.setObjectName("add_btn")
        self.search_layout.addWidget(self.add_btn)
        self.clear_search_btn = QtWidgets.QPushButton(parent=BookmarksWidget)
        self.clear_search_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.clear_search_btn.setObjectName("clear_search_btn")
        self.search_layout.addWidget(self.clear_search_btn)
        self.verticalLayout.addLayout(self.search_layout)
        self.bookmarks_list = QtWidgets.QListWidget(parent=BookmarksWidget)
        self.bookmarks_list.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.bookmarks_list.setStyleSheet("QListWidget {\n"
"    background-color: palette(base);\n"
"    border: 1px solid palette(mid);\n"
"    border-radius: 3px;\n"
"}\n"
"QListWidget::item {\n"
"    border: none;\n"
"    padding: 0px;\n"
"    margin: 2px;\n"
"}\n"
"QListWidget::item:selected {\n"
"    background-color: transparent;\n"
"}\n"
"QListWidget::item:hover {\n"
"    background-color: transparent;\n"
"}")
        self.bookmarks_list.setObjectName("bookmarks_list")
        self.verticalLayout.addWidget(self.bookmarks_list)
        self.groupBoxStats = QtWidgets.QGroupBox(parent=BookmarksWidget)
        self.groupBoxStats.setObjectName("groupBoxStats")
        self.gridLayoutStats = QtWidgets.QGridLayout(self.groupBoxStats)
        self.gridLayoutStats.setObjectName("gridLayoutStats")
        self.labelWithDescription = QtWidgets.QLabel(parent=self.groupBoxStats)
        self.labelWithDescription.setObjectName("labelWithDescription")
        self.gridLayoutStats.addWidget(self.labelWithDescription, 0, 1, 1, 1)
        self.labelTotal = QtWidgets.QLabel(parent=self.groupBoxStats)
        self.labelTotal.setObjectName("labelTotal")
        self.gridLayoutStats.addWidget(self.labelTotal, 0, 0, 1, 1)
        self.labelWithTags = QtWidgets.QLabel(parent=self.groupBoxStats)
        self.labelWithTags.setObjectName("labelWithTags")
        self.gridLayoutStats.addWidget(self.labelWithTags, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBoxStats)

        self.retranslateUi(BookmarksWidget)
        QtCore.QMetaObject.connectSlotsByName(BookmarksWidget)

    def retranslateUi(self, BookmarksWidget):
        _translate = QtCore.QCoreApplication.translate
        BookmarksWidget.setWindowTitle(_translate("BookmarksWidget", "Закладки"))
        self.title_label.setText(_translate("BookmarksWidget", "Веб-закладки"))
        self.search_input.setPlaceholderText(_translate("BookmarksWidget", "Поиск закладок..."))
        self.add_btn.setText(_translate("BookmarksWidget", "➕ Добавить закладку"))
        self.clear_search_btn.setToolTip(_translate("BookmarksWidget", "Очистить поиск"))
        self.clear_search_btn.setText(_translate("BookmarksWidget", "❌"))
        self.groupBoxStats.setTitle(_translate("BookmarksWidget", "Статистика закладок"))
        self.labelWithDescription.setText(_translate("BookmarksWidget", "С описанием: 0"))
        self.labelTotal.setText(_translate("BookmarksWidget", "Всего закладок: 0"))
        self.labelWithTags.setText(_translate("BookmarksWidget", "С тегами: 0"))
