# Form implementation generated from reading ui file 'src/ui/ui_edit_bookmark_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditBookmarkDialog(object):
    def setupUi(self, EditBookmarkDialog):
        EditBookmarkDialog.setObjectName("EditBookmarkDialog")
        EditBookmarkDialog.resize(500, 433)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditBookmarkDialog)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(parent=EditBookmarkDialog)
        self.title_label.setStyleSheet("font-weight: bold;")
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.title_edit = QtWidgets.QLineEdit(parent=EditBookmarkDialog)
        self.title_edit.setObjectName("title_edit")
        self.verticalLayout.addWidget(self.title_edit)
        self.url_label = QtWidgets.QLabel(parent=EditBookmarkDialog)
        self.url_label.setStyleSheet("font-weight: bold;")
        self.url_label.setObjectName("url_label")
        self.verticalLayout.addWidget(self.url_label)
        self.url_edit = QtWidgets.QLineEdit(parent=EditBookmarkDialog)
        self.url_edit.setObjectName("url_edit")
        self.verticalLayout.addWidget(self.url_edit)
        self.description_label = QtWidgets.QLabel(parent=EditBookmarkDialog)
        self.description_label.setStyleSheet("font-weight: bold;")
        self.description_label.setObjectName("description_label")
        self.verticalLayout.addWidget(self.description_label)
        self.description_edit = QtWidgets.QTextEdit(parent=EditBookmarkDialog)
        self.description_edit.setAcceptRichText(False)
        self.description_edit.setObjectName("description_edit")
        self.verticalLayout.addWidget(self.description_edit)
        self.tags_label = QtWidgets.QLabel(parent=EditBookmarkDialog)
        self.tags_label.setStyleSheet("font-weight: bold;")
        self.tags_label.setObjectName("tags_label")
        self.verticalLayout.addWidget(self.tags_label)
        self.tags_edit = QtWidgets.QLineEdit(parent=EditBookmarkDialog)
        self.tags_edit.setObjectName("tags_edit")
        self.verticalLayout.addWidget(self.tags_edit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setSpacing(10)
        self.button_layout.setObjectName("button_layout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.button_layout.addItem(spacerItem1)
        self.cancel_btn = QtWidgets.QPushButton(parent=EditBookmarkDialog)
        self.cancel_btn.setObjectName("cancel_btn")
        self.button_layout.addWidget(self.cancel_btn)
        self.save_btn = QtWidgets.QPushButton(parent=EditBookmarkDialog)
        self.save_btn.setStyleSheet("font-weight: bold;")
        self.save_btn.setObjectName("save_btn")
        self.button_layout.addWidget(self.save_btn)
        self.verticalLayout.addLayout(self.button_layout)

        self.retranslateUi(EditBookmarkDialog)
        QtCore.QMetaObject.connectSlotsByName(EditBookmarkDialog)

    def retranslateUi(self, EditBookmarkDialog):
        _translate = QtCore.QCoreApplication.translate
        EditBookmarkDialog.setWindowTitle(_translate("EditBookmarkDialog", "Редактировать закладку"))
        self.title_label.setText(_translate("EditBookmarkDialog", "Название:"))
        self.title_edit.setPlaceholderText(_translate("EditBookmarkDialog", "Введите название закладки"))
        self.url_label.setText(_translate("EditBookmarkDialog", "URL:"))
        self.url_edit.setPlaceholderText(_translate("EditBookmarkDialog", "https://example.com"))
        self.description_label.setText(_translate("EditBookmarkDialog", "Описание:"))
        self.description_edit.setPlaceholderText(_translate("EditBookmarkDialog", "Добавьте описание закладки..."))
        self.tags_label.setText(_translate("EditBookmarkDialog", "Теги (через запятую):"))
        self.tags_edit.setPlaceholderText(_translate("EditBookmarkDialog", "работа, проекты, ссылки"))
        self.cancel_btn.setText(_translate("EditBookmarkDialog", "Отмена"))
        self.save_btn.setText(_translate("EditBookmarkDialog", "Сохранить"))
