# Form implementation generated from reading ui file 'src/ui/note_editor.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NoteEditorWindow(object):
    def setupUi(self, NoteEditorWindow):
        NoteEditorWindow.setObjectName("NoteEditorWindow")
        NoteEditorWindow.resize(600, 500)
        NoteEditorWindow.setMinimumSize(QtCore.QSize(600, 500))
        self.centralwidget = QtWidgets.QWidget(parent=NoteEditorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setStyleSheet("font-weight: bold;")
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.title_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.title_input.setObjectName("title_input")
        self.verticalLayout.addWidget(self.title_input)
        self.content_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.content_label.setStyleSheet("font-weight: bold;")
        self.content_label.setObjectName("content_label")
        self.verticalLayout.addWidget(self.content_label)
        self.content_editor = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.content_editor.setAcceptRichText(True)
        self.content_editor.setObjectName("content_editor")
        self.verticalLayout.addWidget(self.content_editor)
        self.tags_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.tags_label.setStyleSheet("font-weight: bold;")
        self.tags_label.setObjectName("tags_label")
        self.verticalLayout.addWidget(self.tags_label)
        self.tags_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tags_input.setObjectName("tags_input")
        self.verticalLayout.addWidget(self.tags_input)
        self.status_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.status_label.setStyleSheet("color: gray; font-size: 11px;")
        self.status_label.setObjectName("status_label")
        self.verticalLayout.addWidget(self.status_label)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        self.save_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_btn.setStyleSheet("font-weight: bold;")
        self.save_btn.setObjectName("save_btn")
        self.button_layout.addWidget(self.save_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.button_layout.addItem(spacerItem)
        self.cancel_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cancel_btn.setObjectName("cancel_btn")
        self.button_layout.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.button_layout)
        NoteEditorWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(NoteEditorWindow)
        QtCore.QMetaObject.connectSlotsByName(NoteEditorWindow)

    def retranslateUi(self, NoteEditorWindow):
        _translate = QtCore.QCoreApplication.translate
        NoteEditorWindow.setWindowTitle(_translate("NoteEditorWindow", "Редактор заметки"))
        self.title_label.setText(_translate("NoteEditorWindow", "Заголовок:"))
        self.title_input.setPlaceholderText(_translate("NoteEditorWindow", "Введите заголовок заметки..."))
        self.content_label.setText(_translate("NoteEditorWindow", "Содержимое:"))
        self.content_editor.setPlaceholderText(_translate("NoteEditorWindow", "Введите содержимое заметки..."))
        self.tags_label.setText(_translate("NoteEditorWindow", "Теги (через запятую):"))
        self.tags_input.setPlaceholderText(_translate("NoteEditorWindow", "тег1, тег2, тег3..."))
        self.status_label.setText(_translate("NoteEditorWindow", "⚪ Не сохранено"))
        self.save_btn.setText(_translate("NoteEditorWindow", "💾 Сохранить"))
        self.cancel_btn.setText(_translate("NoteEditorWindow", "❌ Закрыть"))
