# Form implementation generated from reading ui file 'src/ui/note_editor.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NoteEditorWindow(object):
    def setupUi(self, NoteEditorWindow):
        NoteEditorWindow.setObjectName("NoteEditorWindow")
        NoteEditorWindow.resize(280, 300)
        NoteEditorWindow.setMinimumSize(QtCore.QSize(280, 300))
        NoteEditorWindow.setMaximumSize(QtCore.QSize(28000, 30000))
        self.centralwidget = QtWidgets.QWidget(parent=NoteEditorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.content_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.content_label.setStyleSheet("font-weight: bold;")
        self.content_label.setObjectName("content_label")
        self.verticalLayout.addWidget(self.content_label)
        self.content_editor = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.content_editor.setAcceptRichText(True)
        self.content_editor.setObjectName("content_editor")
        self.verticalLayout.addWidget(self.content_editor)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        self.verticalLayout.addLayout(self.button_layout)
        NoteEditorWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(NoteEditorWindow)
        QtCore.QMetaObject.connectSlotsByName(NoteEditorWindow)

    def retranslateUi(self, NoteEditorWindow):
        _translate = QtCore.QCoreApplication.translate
        NoteEditorWindow.setWindowTitle(_translate("NoteEditorWindow", "Редактор заметки"))
        self.content_label.setText(_translate("NoteEditorWindow", "Содержимое:"))
        self.content_editor.setPlaceholderText(_translate("NoteEditorWindow", "Введите содержимое заметки..."))
