# Form implementation generated from reading ui file 'src/ui/settings_widget.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingsWidget(object):
    def setupUi(self, SettingsWidget):
        SettingsWidget.setObjectName("SettingsWidget")
        SettingsWidget.resize(600, 531)
        SettingsWidget.setStyleSheet("SettingsWidget {\n"
"    background-color: palette(window);\n"
"}\n"
"QGroupBox {\n"
"    font-weight: bold;\n"
"    margin-top: 10px;\n"
"    padding-top: 10px;\n"
"    border: 1px solid palette(mid);\n"
"    border-radius: 5px;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 5px 0 5px;\n"
"    color: palette(text);\n"
"}\n"
"QLabel {\n"
"    font-weight: normal;\n"
"}\n"
"QCheckBox {\n"
"    font-weight: normal;\n"
"}\n"
"QComboBox {\n"
"    font-weight: normal;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsWidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.setting_title_label = QtWidgets.QLabel(parent=SettingsWidget)
        self.setting_title_label.setStyleSheet("font-size: 18px; font-weight: bold;")
        self.setting_title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.setting_title_label.setObjectName("setting_title_label")
        self.verticalLayout.addWidget(self.setting_title_label)
        self.appearance_group = QtWidgets.QGroupBox(parent=SettingsWidget)
        self.appearance_group.setObjectName("appearance_group")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.appearance_group)
        self.verticalLayout_2.setContentsMargins(15, 20, 15, 15)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.theme_label = QtWidgets.QLabel(parent=self.appearance_group)
        self.theme_label.setStyleSheet("font-weight: normal;")
        self.theme_label.setObjectName("theme_label")
        self.horizontalLayout.addWidget(self.theme_label)
        self.theme_combo = QtWidgets.QComboBox(parent=self.appearance_group)
        self.theme_combo.setStyleSheet("font-weight: normal;")
        self.theme_combo.setObjectName("theme_combo")
        self.theme_combo.addItem("")
        self.theme_combo.addItem("")
        self.horizontalLayout.addWidget(self.theme_combo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.theme_info_label = QtWidgets.QLabel(parent=self.appearance_group)
        self.theme_info_label.setStyleSheet("font-weight: bold;")
        self.theme_info_label.setObjectName("theme_info_label")
        self.verticalLayout_2.addWidget(self.theme_info_label)
        self.verticalLayout.addWidget(self.appearance_group)
        self.data_group = QtWidgets.QGroupBox(parent=SettingsWidget)
        self.data_group.setObjectName("data_group")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.data_group)
        self.verticalLayout_4.setContentsMargins(15, 20, 15, 15)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.import_btn = QtWidgets.QPushButton(parent=self.data_group)
        self.import_btn.setMinimumSize(QtCore.QSize(180, 45))
        self.import_btn.setStyleSheet("")
        self.import_btn.setObjectName("import_btn")
        self.horizontalLayout_2.addWidget(self.import_btn)
        self.export_btn = QtWidgets.QPushButton(parent=self.data_group)
        self.export_btn.setMinimumSize(QtCore.QSize(180, 45))
        self.export_btn.setStyleSheet("")
        self.export_btn.setObjectName("export_btn")
        self.horizontalLayout_2.addWidget(self.export_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.data_info_label = QtWidgets.QLabel(parent=self.data_group)
        self.data_info_label.setStyleSheet("font-weight: bold;")
        self.data_info_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.data_info_label.setWordWrap(True)
        self.data_info_label.setObjectName("data_info_label")
        self.verticalLayout_4.addWidget(self.data_info_label)
        self.verticalLayout.addWidget(self.data_group)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setSpacing(15)
        self.button_layout.setObjectName("button_layout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.button_layout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.button_layout)

        self.retranslateUi(SettingsWidget)
        QtCore.QMetaObject.connectSlotsByName(SettingsWidget)

    def retranslateUi(self, SettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        SettingsWidget.setWindowTitle(_translate("SettingsWidget", "Настройки"))
        self.setting_title_label.setText(_translate("SettingsWidget", "⚙️ Настройки приложения"))
        self.appearance_group.setTitle(_translate("SettingsWidget", "Внешний вид"))
        self.theme_label.setText(_translate("SettingsWidget", "Тема оформления:"))
        self.theme_combo.setItemText(0, _translate("SettingsWidget", "☀️ Светлая"))
        self.theme_combo.setItemText(1, _translate("SettingsWidget", "🌙 Темная"))
        self.theme_info_label.setText(_translate("SettingsWidget", "💡 Тема приложения сохранится автоматически"))
        self.data_group.setTitle(_translate("SettingsWidget", "Управление данными"))
        self.import_btn.setToolTip(_translate("SettingsWidget", "Импортировать заметки из JSON файла"))
        self.import_btn.setText(_translate("SettingsWidget", "📥 Импорт заметок из JSON"))
        self.export_btn.setToolTip(_translate("SettingsWidget", "Экспортировать заметки в JSON файл"))
        self.export_btn.setText(_translate("SettingsWidget", "📤 Экспорт заметок в JSON"))
        self.data_info_label.setText(_translate("SettingsWidget", "💡 Импорт/экспорт включает заметки, теги и связанные данные"))
