# Form implementation generated from reading ui file 'src/ui/task_widget.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TaskWidget(object):
    def setupUi(self, TaskWidget):
        TaskWidget.setObjectName("TaskWidget")
        TaskWidget.resize(370, 371)
        self.gridLayout_2 = QtWidgets.QGridLayout(TaskWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tasks_header = QtWidgets.QHBoxLayout()
        self.tasks_header.setObjectName("tasks_header")
        self.refresh_btn = QtWidgets.QLabel(parent=TaskWidget)
        self.refresh_btn.setStyleSheet("font-family: \"Times New Roman\";\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"text-align: center;\n"
"qproperty-alignment: \'AlignCenter\';")
        self.refresh_btn.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.refresh_btn.setObjectName("refresh_btn")
        self.tasks_header.addWidget(self.refresh_btn)
        self.verticalLayout.addLayout(self.tasks_header)
        self.tasks_filter = QtWidgets.QHBoxLayout()
        self.tasks_filter.setObjectName("tasks_filter")
        self.sort_combo = QtWidgets.QComboBox(parent=TaskWidget)
        self.sort_combo.setMinimumSize(QtCore.QSize(0, 40))
        self.sort_combo.setStyleSheet("QComboBox {\n"
"    font-family: \"Times New Roman\";\n"
"    font-size: 14px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    font-family: \"Times New Roman\";\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    outline: none;  /* ← Убирает обводку при фокусе */\n"
"    border: none;   /* ← Убирает границу если есть */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 8px 12px;\n"
"    outline: none;  /* ← Убирает обводку у пунктов */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #e0e0e0;\n"
"    color: black;\n"
"    outline: none;  /* ← Убирает обводку у выбранного пункта */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #FFAA00;\n"
"    outline: none;  /* ← Убирает обводку при наведении */\n"
"}")
        self.sort_combo.setObjectName("sort_combo")
        self.sort_combo.addItem("")
        self.sort_combo.addItem("")
        self.sort_combo.addItem("")
        self.tasks_filter.addWidget(self.sort_combo)
        self.filter_combo = QtWidgets.QComboBox(parent=TaskWidget)
        self.filter_combo.setMinimumSize(QtCore.QSize(0, 40))
        self.filter_combo.setStyleSheet("QComboBox {\n"
"    font-family: \"Times New Roman\";\n"
"    font-size: 14px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    font-family: \"Times New Roman\";\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    outline: none;  /* ← Убирает обводку при фокусе */\n"
"    border: none;   /* ← Убирает границу если есть */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 8px 12px;\n"
"    outline: none;  /* ← Убирает обводку у пунктов */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #e0e0e0;\n"
"    color: black;\n"
"    outline: none;  /* ← Убирает обводку у выбранного пункта */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #FFAA00;\n"
"    outline: none;  /* ← Убирает обводку при наведении */\n"
"}")
        self.filter_combo.setEditable(False)
        self.filter_combo.setObjectName("filter_combo")
        self.filter_combo.addItem("")
        self.filter_combo.addItem("")
        self.filter_combo.addItem("")
        self.tasks_filter.addWidget(self.filter_combo)
        self.verticalLayout.addLayout(self.tasks_filter)
        self.tasks_list = QtWidgets.QListWidget(parent=TaskWidget)
        self.tasks_list.setObjectName("tasks_list")
        self.verticalLayout.addWidget(self.tasks_list)
        self.groupBoxStats = QtWidgets.QGroupBox(parent=TaskWidget)
        self.groupBoxStats.setObjectName("groupBoxStats")
        self.gridLayoutStats = QtWidgets.QGridLayout(self.groupBoxStats)
        self.gridLayoutStats.setObjectName("gridLayoutStats")
        self.total_label = QtWidgets.QLabel(parent=self.groupBoxStats)
        self.total_label.setStyleSheet("font-weight: bold;")
        self.total_label.setObjectName("total_label")
        self.gridLayoutStats.addWidget(self.total_label, 0, 0, 1, 1)
        self.active_label = QtWidgets.QLabel(parent=self.groupBoxStats)
        self.active_label.setObjectName("active_label")
        self.gridLayoutStats.addWidget(self.active_label, 0, 1, 1, 1)
        self.completed_label = QtWidgets.QLabel(parent=self.groupBoxStats)
        self.completed_label.setObjectName("completed_label")
        self.gridLayoutStats.addWidget(self.completed_label, 0, 2, 1, 1)
        self.high_priority_label = QtWidgets.QLabel(parent=self.groupBoxStats)
        self.high_priority_label.setObjectName("high_priority_label")
        self.gridLayoutStats.addWidget(self.high_priority_label, 1, 0, 1, 1)
        self.overdue_label = QtWidgets.QLabel(parent=self.groupBoxStats)
        self.overdue_label.setObjectName("overdue_label")
        self.gridLayoutStats.addWidget(self.overdue_label, 1, 1, 1, 1)
        self.with_deadline_label = QtWidgets.QLabel(parent=self.groupBoxStats)
        self.with_deadline_label.setStyleSheet("")
        self.with_deadline_label.setObjectName("with_deadline_label")
        self.gridLayoutStats.addWidget(self.with_deadline_label, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBoxStats)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)

        self.retranslateUi(TaskWidget)
        QtCore.QMetaObject.connectSlotsByName(TaskWidget)

    def retranslateUi(self, TaskWidget):
        _translate = QtCore.QCoreApplication.translate
        TaskWidget.setWindowTitle(_translate("TaskWidget", "Form"))
        self.refresh_btn.setText(_translate("TaskWidget", "Предстоящие задачи"))
        self.sort_combo.setItemText(0, _translate("TaskWidget", "По дате создания"))
        self.sort_combo.setItemText(1, _translate("TaskWidget", "По сроку выполнения"))
        self.sort_combo.setItemText(2, _translate("TaskWidget", "По приоритету"))
        self.filter_combo.setItemText(0, _translate("TaskWidget", "Все задачи"))
        self.filter_combo.setItemText(1, _translate("TaskWidget", "Только активные"))
        self.filter_combo.setItemText(2, _translate("TaskWidget", "Только выполненные"))
        self.groupBoxStats.setTitle(_translate("TaskWidget", "Статистика задач"))
        self.total_label.setText(_translate("TaskWidget", "Всего: 0"))
        self.active_label.setText(_translate("TaskWidget", "Активные: 0"))
        self.completed_label.setText(_translate("TaskWidget", "Выполнено: 0"))
        self.high_priority_label.setText(_translate("TaskWidget", "Высокий приоритет: 0"))
        self.overdue_label.setText(_translate("TaskWidget", "Просрочено: 0"))
        self.with_deadline_label.setText(_translate("TaskWidget", "С дедлайном: 0"))
