# Form implementation generated from reading ui file 'src/ui/task_widget.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TaskWidget(object):
    def setupUi(self, TaskWidget):
        TaskWidget.setObjectName("TaskWidget")
        TaskWidget.resize(370, 371)
        self.gridLayout_2 = QtWidgets.QGridLayout(TaskWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tasks_header = QtWidgets.QHBoxLayout()
        self.tasks_header.setObjectName("tasks_header")
        self.refresh_btn = QtWidgets.QLabel(parent=TaskWidget)
        self.refresh_btn.setStyleSheet("font-family: \"Times New Roman\";\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"text-align: center;\n"
"qproperty-alignment: \'AlignCenter\';")
        self.refresh_btn.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.refresh_btn.setObjectName("refresh_btn")
        self.tasks_header.addWidget(self.refresh_btn)
        self.pushButton = QtWidgets.QPushButton(parent=TaskWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton.setObjectName("pushButton")
        self.tasks_header.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.tasks_header)
        self.tasks_filter = QtWidgets.QHBoxLayout()
        self.tasks_filter.setObjectName("tasks_filter")
        self.filter_combo = QtWidgets.QComboBox(parent=TaskWidget)
        self.filter_combo.setMinimumSize(QtCore.QSize(0, 40))
        self.filter_combo.setStyleSheet("QComboBox {\n"
"    font-family: \"Times New Roman\";\n"
"    font-size: 14px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    font-family: \"Times New Roman\";\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    outline: none;  /* ← Убирает обводку при фокусе */\n"
"    border: none;   /* ← Убирает границу если есть */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 8px 12px;\n"
"    outline: none;  /* ← Убирает обводку у пунктов */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #e0e0e0;\n"
"    color: black;\n"
"    outline: none;  /* ← Убирает обводку у выбранного пункта */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #FFAA00;\n"
"    outline: none;  /* ← Убирает обводку при наведении */\n"
"}")
        self.filter_combo.setEditable(False)
        self.filter_combo.setObjectName("filter_combo")
        self.filter_combo.addItem("")
        self.filter_combo.addItem("")
        self.filter_combo.addItem("")
        self.tasks_filter.addWidget(self.filter_combo)
        self.verticalLayout.addLayout(self.tasks_filter)
        self.tasks_list = QtWidgets.QListWidget(parent=TaskWidget)
        self.tasks_list.setObjectName("tasks_list")
        self.verticalLayout.addWidget(self.tasks_list)
        self.tasks_stats = QtWidgets.QHBoxLayout()
        self.tasks_stats.setObjectName("tasks_stats")
        self.completed_label = QtWidgets.QLabel(parent=TaskWidget)
        self.completed_label.setObjectName("completed_label")
        self.tasks_stats.addWidget(self.completed_label)
        self.active_label = QtWidgets.QLabel(parent=TaskWidget)
        self.active_label.setObjectName("active_label")
        self.tasks_stats.addWidget(self.active_label)
        self.total_label = QtWidgets.QLabel(parent=TaskWidget)
        self.total_label.setObjectName("total_label")
        self.tasks_stats.addWidget(self.total_label)
        self.verticalLayout.addLayout(self.tasks_stats)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)

        self.retranslateUi(TaskWidget)
        QtCore.QMetaObject.connectSlotsByName(TaskWidget)

    def retranslateUi(self, TaskWidget):
        _translate = QtCore.QCoreApplication.translate
        TaskWidget.setWindowTitle(_translate("TaskWidget", "Form"))
        self.refresh_btn.setText(_translate("TaskWidget", "Предстоящие задачи"))
        self.pushButton.setText(_translate("TaskWidget", "🔄 Обновить"))
        self.filter_combo.setItemText(0, _translate("TaskWidget", "Все задачи"))
        self.filter_combo.setItemText(1, _translate("TaskWidget", "Только активные"))
        self.filter_combo.setItemText(2, _translate("TaskWidget", "Только выполненные"))
        self.completed_label.setText(_translate("TaskWidget", "Выполнено: "))
        self.active_label.setText(_translate("TaskWidget", "Активные: "))
        self.total_label.setText(_translate("TaskWidget", "Всего: "))
